DROP DATABASE SURVEY IF EXISTS;
CREATE DATABASE SURVEY;
USE SURVEY;

CREATE TABLE USERS (
	EMAIL_ID VARCHAR(20),
	PASSWORD VARCHAR(20),
	NAME VARCHAR(20),
	ID INT AUTO_INCREMENT,
	ROLE VARCHAR(20),
	PRIMARY KEY (ID)
);

CREATE TABLE ORGANIZER (
	ID INT REFERENCES USERS (ID),
	PRIMARY KEY (ID)
);

CREATE TABLE SURVEY (
	ORGANIZER_ID INT REFERENCES ORGANIZER (ID),
	ID INT,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	STATUS INT (1),
	PRIMARY KEY (ORGANIZER_ID, ID)
);

CREATE TABLE QUESTION (
	SURVEY_ID INT REFERENCES SURVEY (ID),
	ID INT,
	QUESTION_TYPE VARCHAR (10),
	QUESTION VARCHAR (255),
	PRIMARY KEY (SURVEY_ID, ID)
);

CREATE TABLE DISCRETE_ANSWERABLE (
	QUESTION_ID INT REFERENCES QUESTION (ID),
	ID INT,
	OPTION_TEXT VARCHAR (10),
	PRIMARY KEY (QUESTION_ID, ID)
);

CREATE TABLE DESCRIPTIVE_ANSWERABLE (
	QUESTION_ID INT REFERENCES QUESTION (ID),
	MEDIA_FILE_TYPE INT (1),
	MEDIA_FILE_LOCATION VARCHAR(255),
	PRIMARY KEY (QUESTION_ID)
);

CREATE TABLE PARTICIPANT (
	ID INT REFERENCES USERS (ID),
	PRIMARY KEY (ID)
);

CREATE TABLE SURVEY_ATTEMPTED (
	ORGANIZER_ID INT REFERENCES ORGANIZER (ID),
	SURVEY_ID INT REFERENCES SURVEY (ID),
	PARTICIPANT_ID INT REFERENCES PARTICIPANT (ID),
	ATTEMPTED_TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE DISCRETE_ANSWERS (
	ORGANIZER_ID INT REFERENCES ORGANIZER (ID),
	SURVEY_ID INT REFERENCES SURVEY (ID),
	PARTICIPANT_ID INT REFERENCES PARTICIPANT (ID),
	QUESTION_ID INT REFERENCES DISCRETE_ANSWERABLE (QUESTION_ID),
	OPTION_ID INT REFERENCES DISCRETE_ANSWERABLE (ID)
);

CREATE TABLE DESCRIPTIVE_ANSWERS (
	ORGANIZER_ID INT REFERENCES ORGANIZER (ID),
	SURVEY_ID INT REFERENCES SURVEY (ID),
	PARTICIPANT_ID INT REFERENCES PARTICIPANT (ID),
	QUESTION_ID INT REFERENCES DESCRIPTIVE_ANSWERABLE (QUESTION_ID),
	ANSWER_TEXT VARCHAR (255),
	MEDIA_FILE_TYPE INT (1),
	MEDIA_FILE_LOCATION VARCHAR(255)
);